server:
  servlet:
    session:
      timeout: 600000
      cookie:
        name: UISESSION
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json, image/svg+xml
    min-response-size: 1024
spring:
  application:
    name: GatewayMain
  boot:
    admin:
      client:
        url:
        - http://administrator:8080
  servlet:
    multipart:
      max-file-size: 102400KB
      max-request-size: 102400KB
  rabbitmq:
    host: 192.168.4.101
    port: 5672
    username: guest
    password: guest
  database: 
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://video-postgres:5432/config_db
    username: kavenegar
    password: k@venegardotio
  jpa:
    database: POSTGRESQL
    hibernate:
       ddl-auto: update
    generate-ddl: true 
eureka:
  client:
    service-url:
      defaultZone: http://video-discovery-service:8080/eureka
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
ribbon:
  ReadTimeout: 100000000
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000000
        readTimeout: 60000000
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000000
zuul:
  sensitive-headers: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 60000000
    socket-timeout-millis: 60000000
    time-to-live: 60000000
  routes:
    uaa:
      path: /UAA/**
      service-id: uaa
    video-service:
      path: /VideoService/**
      service-id: VideoService

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  path: log
  file: 
    max-size: 5MB
    max-history: 100
jwt:
  token:
    header-name: Authorization
project:
  key: AVA_NEGAR_PROJECT
security:
  oauth2:
    client:
      client-id: AVA_NEGAR_PROJECT
      client-secret: AVA_NEGAR_PROJECT_SECRET
##### clientId + ":" + clientSecret //please change base64
      client-id-and-secret-in-base-64: R2F0ZXdheUNsYXNzSWQ6R2F0ZXdheUNsYXNzU2VjcmV0
      grant-type: password
#      access-token-uri: http://uaa:8080/oauth/token
#      user-authorization-uri: http://uaa:8080/oauth/authorize
    resource:
      user-info-uri: http://uaa:8080/account/principal
