server:
  host-address-authentication: http://192.168.4.101:8000
  host-address-signin-session: http://192.168.4.101:8024
  host-address-microservice-drive: http://192.168.4.101:8016
  host-address-microservice-notification: http://192.168.4.101:8080
  host-address-microservice-messaging: http://192.168.4.101:8081
  servlet:
    session:
      timeout: 600000
      cookie:
        name: UISESSION
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json, image/svg+xml
    min-response-size: 1024
spring:
  application:
    name: GatewayMain
  profiles:
    active:
    - dev
  boot:
    admin:
      client:
        url:
        - http://192.168.4.101:8022
  servlet:
    multipart:
      max-file-size: 102400KB
      max-request-size: 102400KB
  rabbitmq:
    host: 192.168.4.101
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8021/eureka
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
ribbon:
  ReadTimeout: 100000000
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000000
        readTimeout: 60000000
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000000
zuul:
  sensitive-headers: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    time-to-live: 60000
  routes:
    uaa:
      path: /UAA/**
      service-id: UAA

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  path: log
  file: 
    max-size: 5MB
    max-history: 20
jwt:
  token:
    header-name: Authorization
    header-name-uaa: AuthorizationUAA
    header-name-sub-uaa: AuthorizationSubUAA
project:
  key: AVA_NEGAR_PROJECT
security:
  oauth2:
    client:
      client-id: GatewayClassId
      client-secret: GatewayClassSecret
      client-id-and-secret-in-base-64: R2F0ZXdheUNsYXNzSWQ6R2F0ZXdheUNsYXNzU2VjcmV0 # base64 of clientId:clientSecret
      grant-type: password
#      access-token-uri: http://192.168.4.101:8010/oauth/token
#      user-authorization-uri: http://192.168.4.101:8010/oauth/authorize
 
