server:
  servlet:
    session:
      timeout: 600000
      cookie:
        name: UISESSION
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json
    min-response-size: 1024
spring:
  application:
    name: MicroserviceVideo
  profiles:
    active:
    - dev
  boot:
    admin:
      client:
        url:
        - http://192.168.4.101:8022
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB
  data:
    redis:
      hostname: video-redis
      port: 6379
      password: kavenegardotio
  rabbitmq:
    host: video-rabbitmq
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://video-discovery-service:8080/eureka
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
ribbon:
  ReadTimeout: 100000000
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000000
        readTimeout: 60000000
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  path: log
  file: 
    max-size: 5MB
    max-history: 20
jwt:
  token:
    header-name: Authorization
project:
  key: AVA_NEGAR_PROJECT
security:
  oauth2:
    client:
      client-id: MicroserviceVideo
      client-secret: MicroserviceVideo
#      access-token-uri: http://192.168.4.101:8010/oauth/token
#      user-authorization-uri: http://192.168.4.101:8010/oauth/authorize
    resource:
      user-info-uri: http://localhost:8010/account/principal
