server:
  host-address-authentication: http://94.232.173.157:8000
  servlet:
    session:
      timeout: 600000
      cookie:
        name: UISESSION
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
spring:
  application:
    name: UAA
  boot:
    admin:
      client:
        url:
        - http://administrator:8080
  jpa:
    database: POSTGRESQL
    generate-ddl: true 
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://voice.kavenegar.com:7000/avanegar_db 
    username: kavenegar
    password: k@venegardotio
  database:
    driverClassName: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://video-discovery-service:8080/eureka
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
ribbon:
  ReadTimeout: 100000000
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000000
        readTimeout: 60000000
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  path: log
  file: 
    max-size: 5MB
    max-history: 100
jwt:
  token:
    access-token-validity-seconds: 700000
    support-refresh-token: true
    header-name: Authorization

project:
  key: AVA_NEGAR_PROJECT
security:
  oauth2:
    client:
      client-id: UAAId
      client-secret: UAASecret
